package homereset

import (
	"crypto/rand"
	"encoding/json"
	"errors"
	"fmt"
	"io/fs"
	"math/big"
	"os"
	"os/exec"
	"os/user"
	"path/filepath"
	"strconv"
	"strings"
	"syscall"

	"golang.org/x/sys/unix"
)

const snapshotRoot = "/var/lib/home-snapshots"
const resetState = snapshotRoot + "/.workspace-reset"
const publishedSnapshots = snapshotRoot + "/workspace"

// Config is generated by the system configuration, not supplied by a student
// or a reset CLI. Runtime integration must keep the login barrier held until
// Reset returns successfully and must never automatically retry a failure.
type Config struct {
	User           string   `json:"user"`
	Seed           string   `json:"seed"`
	EphemeralPaths []string `json:"ephemeralPaths"`
	Wallpapers     []string `json:"wallpapers"`
	Btrfs          string   `json:"btrfs"`
	Dconf          string   `json:"dconf"`
	Systemctl      string   `json:"systemctl"`
}

type resetAccount struct {
	uid, gid, snapshotGID int
	home                  string
}

// Reset implements a boot-only, fail-closed reset. A durable pending record
// survives process failure and reboot. It is deliberately not a recovery API:
// an administrator must inspect incomplete work before any subsequent attempt.
func Reset(config Config) error { return runReset(config, copyTree) }

func runReset(config Config, restore func(string, string, int, int) error) error {
	account, err := preflight(config)
	if err != nil {
		return fmt.Errorf("reset preflight: %w", err)
	}
	if err := privateDirectory(resetState, 0700, 0); err != nil {
		return err
	}
	lock, err := os.OpenFile(resetState+"/lock", os.O_CREATE|os.O_RDWR|syscall.O_NOFOLLOW, 0600)
	if err != nil {
		return err
	}
	defer lock.Close()
	if err := unix.Flock(int(lock.Fd()), unix.LOCK_EX|unix.LOCK_NB); err != nil {
		return errors.New("another reset owns the lock")
	}
	if err := inspectState(); err != nil {
		return err
	}
	if err := privateDirectory(publishedSnapshots, 0750, account.snapshotGID); err != nil {
		return err
	}
	if err := inspectSnapshots(config); err != nil {
		return err
	}
	// Repeat the session guard after acquiring the lock and inspecting storage.
	if err := loginBarrier(config, account.uid); err != nil {
		return err
	}
	if err := writeExclusive(resetState+"/pending.json", []byte(`{"schemaVersion":1,"seed":`+strconv.Quote(config.Seed)+`,"user":`+strconv.Quote(config.User)+"}\n")); err != nil {
		return err
	}
	// Every error below retains pending.json, including an interrupted seed copy.
	// Do not install an EXIT handler that removes evidence or retries the reset.
	if err := os.Mkdir(resetState+"/prepared", 0700); err != nil {
		return err
	}
	if err := copyTree(config.Seed+"/home", resetState+"/prepared", 0, 0); err != nil {
		return err
	}
	if err := prepareWallpaper(config); err != nil {
		return err
	}
	if err := loginBarrier(config, account.uid); err != nil {
		return err
	}
	if err := command(config.Btrfs, "subvolume", "snapshot", account.home, resetState+"/previous"); err != nil {
		return err
	}
	// The snapshot is initially reachable only by root. Sanitize it before
	// publication, leaving the original home untouched if exclusions fail.
	if err := RemoveEphemeral(resetState+"/previous", config.EphemeralPaths); err != nil {
		return err
	}
	if err := snapshotPermissions(resetState+"/previous", account.snapshotGID); err != nil {
		return err
	}
	if err := command(config.Btrfs, "property", "set", "-ts", resetState+"/previous", "ro", "true"); err != nil {
		return err
	}
	if err := syncFilesystem(resetState); err != nil {
		return err
	}
	if err := loginBarrier(config, account.uid); err != nil {
		return err
	}
	if err := cleanHome(account.home, true); err != nil {
		return err
	}
	if err := restore(resetState+"/prepared", account.home, account.uid, account.gid); err != nil {
		return fmt.Errorf("home restore incomplete; login must remain blocked: %w", err)
	}
	if err := os.Chmod(account.home, 0700); err != nil {
		return err
	}
	if err := syncFilesystem(account.home); err != nil {
		return err
	}
	if err := publishSnapshot(config, account.snapshotGID); err != nil {
		return err
	}
	if err := cleanHome(resetState+"/prepared", true); err != nil {
		return err
	}
	if err := os.Remove(resetState + "/prepared"); err != nil {
		return err
	}
	if _, err := os.Lstat(resetState + "/keyfiles"); err == nil {
		if err := cleanHome(resetState+"/keyfiles", true); err != nil {
			return err
		}
		if err := os.Remove(resetState + "/keyfiles"); err != nil {
			return err
		}
	} else if !errors.Is(err, os.ErrNotExist) {
		return err
	}
	boot, err := readBounded("/proc/sys/kernel/random/boot_id", 128)
	if err != nil {
		return err
	}
	receipt, err := json.Marshal(struct {
		SchemaVersion int    `json:"schemaVersion"`
		Seed          string `json:"seed"`
		User          string `json:"user"`
		BootID        string `json:"bootID"`
	}{1, config.Seed, config.User, strings.TrimSpace(string(boot))})
	if err != nil {
		return err
	}
	if err := writeExclusive(resetState+"/success.new", receipt); err != nil {
		return err
	}
	if err := os.Rename(resetState+"/success.new", resetState+"/success.json"); err != nil {
		return err
	}
	if err := syncFilesystem(resetState); err != nil {
		return err
	}
	if err := os.Remove(resetState + "/pending.json"); err != nil {
		return err
	}
	return syncFilesystem(resetState)
}

func preflight(config Config) (resetAccount, error) {
	var account resetAccount
	if os.Geteuid() != 0 {
		return account, errors.New("reset requires root")
	}
	if config.User == "" || config.User == "admin" || strings.ContainsAny(config.User, "/\\\x00\n\r ") {
		return account, errors.New("invalid managed account")
	}
	identity, err := user.Lookup(config.User)
	if err != nil {
		return account, err
	}
	account.uid, err = strconv.Atoi(identity.Uid)
	if err != nil || account.uid < 1000 || account.uid == 65534 {
		return account, errors.New("managed account must be a normal user")
	}
	account.gid, err = strconv.Atoi(identity.Gid)
	if err != nil {
		return account, err
	}
	group, err := user.LookupGroup("veyon-master")
	if err != nil {
		return account, err
	}
	account.snapshotGID, err = strconv.Atoi(group.Gid)
	if err != nil {
		return account, err
	}
	account.home = "/home/" + config.User
	if identity.HomeDir != account.home {
		return account, errors.New("managed account home differs from the configured path")
	}
	if err := validatePaths(config.EphemeralPaths); err != nil {
		return account, err
	}
	if err := validateSeed(config.Seed); err != nil {
		return account, err
	}
	for _, tool := range []struct{ path, base string }{{config.Btrfs, "btrfs"}, {config.Dconf, "dconf"}, {config.Systemctl, "systemctl"}} {
		if filepath.Base(tool.path) != tool.base {
			return account, errors.New("unexpected reset tool")
		}
		if err := immutableStoreFile(tool.path); err != nil {
			return account, err
		}
	}
	if len(config.Wallpapers) > 128 {
		return account, errors.New("too many wallpapers")
	}
	for _, wallpaper := range config.Wallpapers {
		if err := immutableStoreFile(wallpaper); err != nil {
			return account, err
		}
	}
	if err := trustedDirectory("/home"); err != nil {
		return account, err
	}
	if err := trustedDirectory(snapshotRoot); err != nil {
		return account, err
	}
	home, err := mountedSubvolume(account.home, "/@home-"+config.User)
	if err != nil {
		return account, err
	}
	snapshots, err := mountedSubvolume(snapshotRoot, "/@snapshots")
	if err != nil {
		return account, err
	}
	// Btrfs reports a different st_dev for each subvolume. Do not compare it
	// across these roots. The snapshot ioctl additionally requires the same
	// filesystem and must succeed before any original home data is removed.
	if home.Mnt_id == snapshots.Mnt_id {
		return account, errors.New("home and snapshots must have distinct mounts")
	}
	if home.Uid != uint32(account.uid) || home.Gid != uint32(account.gid) || home.Mode&0777 != 0700 {
		return account, errors.New("unexpected home ownership or permissions")
	}
	if err := loginBarrier(config, account.uid); err != nil {
		return account, err
	}
	if err := cleanSelected(account.home, config.EphemeralPaths, false); err != nil {
		return account, err
	}
	if err := cleanHome(account.home, false); err != nil {
		return account, err
	}
	return account, nil
}

func trustedDirectory(name string) error {
	if !filepath.IsAbs(name) || filepath.Clean(name) != name {
		return errors.New("noncanonical trusted directory")
	}
	for current := name; ; current = filepath.Dir(current) {
		info, err := os.Lstat(current)
		if err != nil {
			return err
		}
		if !info.IsDir() || info.Sys().(*syscall.Stat_t).Uid != 0 || info.Mode().Perm()&0022 != 0 {
			return fmt.Errorf("untrusted reset directory: %s", current)
		}
		if current == "/" {
			return nil
		}
	}
}

func privateDirectory(name string, mode os.FileMode, gid int) error {
	if err := trustedDirectory(filepath.Dir(name)); err != nil {
		return err
	}
	err := os.Mkdir(name, mode)
	if err == nil {
		if err := os.Chown(name, 0, gid); err != nil {
			return err
		}
	} else if !errors.Is(err, os.ErrExist) {
		return err
	}
	if err := trustedDirectory(name); err != nil {
		return err
	}
	info, err := os.Lstat(name)
	if err != nil {
		return err
	}
	if info.Mode().Perm() != mode || info.Sys().(*syscall.Stat_t).Gid != uint32(gid) {
		return errors.New("unexpected reset directory permissions")
	}
	return nil
}

func mountedSubvolume(name, subvolume string) (unix.Statx_t, error) {
	var result unix.Statx_t
	err := withDirectory(name, func(fd int, stat unix.Statx_t) error {
		var filesystem unix.Statfs_t
		if err := unix.Fstatfs(fd, &filesystem); err != nil {
			return err
		}
		if filesystem.Type != unix.BTRFS_SUPER_MAGIC || stat.Ino != 256 || stat.Mask&unix.STATX_SUBVOL == 0 {
			return errors.New("expected a Btrfs subvolume root")
		}
		mounts, err := os.ReadFile("/proc/self/mountinfo")
		if err != nil {
			return err
		}
		for _, line := range strings.Split(string(mounts), "\n") {
			fields := strings.Fields(line)
			if len(fields) > 6 && fields[0] == strconv.FormatUint(stat.Mnt_id, 10) && fields[3] == subvolume && fields[4] == name {
				result = stat
				return nil
			}
		}
		return errors.New("home or snapshot mount does not match the declared layout")
	})
	return result, err
}

func loginBarrier(config Config, uid int) error {
	if _, err := os.Lstat("/var/lib/systemd/linger/" + config.User); !errors.Is(err, os.ErrNotExist) {
		return errors.New("managed account must not have lingering enabled")
	}
	info, err := os.Lstat("/run/nologin")
	if err != nil {
		return errors.New("login barrier is not held")
	}
	if !info.Mode().IsRegular() || info.Sys().(*syscall.Stat_t).Uid != 0 || info.Mode().Perm()&0022 != 0 {
		return errors.New("untrusted login barrier")
	}
	for _, unit := range []string{"systemd-user-sessions.service", "display-manager.service"} {
		output, err := exec.Command(config.Systemctl, "show", "--property=ActiveState", "--value", unit).Output()
		if err != nil {
			return errors.New("cannot establish login service state")
		}
		if state := strings.TrimSpace(string(output)); state != "inactive" && state != "failed" {
			return errors.New("login services must be stopped before reset")
		}
	}
	entries, err := os.ReadDir("/proc")
	if err != nil {
		return err
	}
	for _, entry := range entries {
		if _, err := strconv.Atoi(entry.Name()); err != nil {
			continue
		}
		data, err := os.ReadFile("/proc/" + entry.Name() + "/status")
		if errors.Is(err, os.ErrNotExist) {
			continue
		}
		if err != nil {
			return err
		}
		found := false
		for _, line := range strings.Split(string(data), "\n") {
			if !strings.HasPrefix(line, "Uid:") {
				continue
			}
			fields := strings.Fields(line)
			if len(fields) != 5 {
				return errors.New("cannot establish process ownership")
			}
			found = true
			for _, field := range fields[1:] {
				if field == strconv.Itoa(uid) {
					return errors.New("managed account still has running processes")
				}
			}
		}
		if !found {
			return errors.New("cannot establish process ownership")
		}
	}
	return nil
}

func inspectState() error {
	entries, err := os.ReadDir(resetState)
	if err != nil {
		return err
	}
	for _, entry := range entries {
		if entry.Name() != "lock" && entry.Name() != "success.json" {
			return errors.New("incomplete reset evidence exists; administrator recovery is required")
		}
		info, err := entry.Info()
		if err != nil {
			return err
		}
		if !info.Mode().IsRegular() || info.Mode().Perm() != 0600 || info.Sys().(*syscall.Stat_t).Uid != 0 {
			return errors.New("untrusted reset state")
		}
	}
	return nil
}

func inspectSnapshots(config Config) error {
	if _, err := os.Lstat(publishedSnapshots); errors.Is(err, os.ErrNotExist) {
		return nil
	} else if err != nil {
		return err
	}
	if err := trustedDirectory(publishedSnapshots); err != nil {
		return err
	}
	entries, err := os.ReadDir(publishedSnapshots)
	if err != nil {
		return err
	}
	for _, entry := range entries {
		if len(entry.Name()) != len("snapshot-1") || entry.Name() < "snapshot-1" || entry.Name() > "snapshot-5" {
			return errors.New("unexpected managed snapshot entry")
		}
		name := publishedSnapshots + "/" + entry.Name()
		if err := trustedDirectory(name); err != nil {
			return err
		}
		if err := withDirectory(name, func(fd int, stat unix.Statx_t) error {
			parent, err := statEntry(unix.AT_FDCWD, publishedSnapshots, 0)
			if err != nil {
				return err
			}
			if stat.Ino != 256 || stat.Subvol == parent.Subvol || stat.Mnt_id != parent.Mnt_id {
				return errors.New("invalid managed snapshot subvolume")
			}
			return nil
		}); err != nil {
			return err
		}
		output, err := exec.Command(config.Btrfs, "property", "get", "-ts", name, "ro").Output()
		if err != nil || strings.TrimSpace(string(output)) != "ro=true" {
			return errors.New("managed snapshot is not read-only")
		}
	}
	return nil
}

func snapshotPermissions(name string, gid int) error {
	// Only the new private snapshot is traversed. Never chmod/chown a symlink
	// target, and never let staff see the snapshot before exclusion is complete.
	return filepath.WalkDir(name, func(path string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if entry.Type()&os.ModeSymlink != 0 {
			return nil
		}
		if err := os.Lchown(path, 0, gid); err != nil {
			return err
		}
		mode := os.FileMode(0640)
		if entry.IsDir() {
			mode = 0750
		}
		return os.Chmod(path, mode)
	})
}

func publishSnapshot(config Config, gid int) error {
	if err := privateDirectory(publishedSnapshots, 0750, gid); err != nil {
		return err
	}
	if _, err := os.Lstat(publishedSnapshots + "/snapshot-5"); err == nil {
		if err := command(config.Btrfs, "subvolume", "delete", publishedSnapshots+"/snapshot-5"); err != nil {
			return err
		}
	} else if !errors.Is(err, os.ErrNotExist) {
		return err
	}
	for i := 4; i >= 1; i-- {
		from := publishedSnapshots + "/snapshot-" + strconv.Itoa(i)
		if _, err := os.Lstat(from); errors.Is(err, os.ErrNotExist) {
			continue
		} else if err != nil {
			return err
		}
		if err := os.Rename(from, publishedSnapshots+"/snapshot-"+strconv.Itoa(i+1)); err != nil {
			return err
		}
	}
	// A read-only subvolume cannot be moved between different parents. Keep
	// the recovery copy read-only and publish another cheap metadata snapshot.
	if err := command(config.Btrfs, "subvolume", "snapshot", "-r", resetState+"/previous", publishedSnapshots+"/snapshot-1"); err != nil {
		return err
	}
	if err := command(config.Btrfs, "subvolume", "delete", resetState+"/previous"); err != nil {
		return err
	}
	return syncFilesystem(publishedSnapshots)
}

func prepareWallpaper(config Config) error {
	if len(config.Wallpapers) == 0 {
		return nil
	}
	index, err := rand.Int(rand.Reader, big.NewInt(int64(len(config.Wallpapers))))
	if err != nil {
		return err
	}
	picture := "file://" + config.Wallpapers[index.Int64()]
	if err := os.Mkdir(resetState+"/keyfiles", 0700); err != nil {
		return err
	}
	if err := copyFile(config.Seed+"/dconf/00-workspace", resetState+"/keyfiles/00-workspace"); err != nil {
		return err
	}
	text := "[org/gnome/desktop/background]\npicture-uri='" + picture + "'\npicture-uri-dark='" + picture + "'\npicture-options='zoom'\n\n[org/gnome/desktop/screensaver]\npicture-uri='" + picture + "'\npicture-options='zoom'\n"
	if err := writeExclusive(resetState+"/keyfiles/90-wallpaper", []byte(text)); err != nil {
		return err
	}
	if err := os.MkdirAll(resetState+"/prepared/.config/dconf", 0700); err != nil {
		return err
	}
	return command(config.Dconf, "compile", resetState+"/prepared/.config/dconf/user", resetState+"/keyfiles")
}

func writeExclusive(name string, data []byte) error {
	file, err := os.OpenFile(name, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0600)
	if err != nil {
		return err
	}
	_, writeErr := file.Write(data)
	syncErr := file.Sync()
	closeErr := file.Close()
	if err := errors.Join(writeErr, syncErr, closeErr); err != nil {
		return err
	}
	return syncFilesystem(filepath.Dir(name))
}

func syncFilesystem(name string) error {
	fd, err := unix.Open(name, unix.O_RDONLY|unix.O_DIRECTORY|unix.O_CLOEXEC|unix.O_NOFOLLOW, 0)
	if err != nil {
		return err
	}
	defer unix.Close(fd)
	return unix.Syncfs(fd)
}

func command(binary string, args ...string) error {
	cmd := exec.Command(binary, args...)
	cmd.Env = []string{"LANG=C", "LC_ALL=C"}
	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("%s failed: %w: %s", filepath.Base(binary), err, strings.TrimSpace(string(output)))
	}
	return nil
}
